/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sun.glb --types --transform 
Files: sun.glb [2.12MB] > /Users/aris/Aris_ws/MyBolgWeb/my-web-fontend/public/sun-transformed.glb [476.5KB] (77%)
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-9ef1c68fbb944147bcfcc891d3912645
Title: Sun
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    UnstableStarCore_1_0: THREE.Mesh
    UnstableStarref_2_0: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    material_1: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/sun-transformed.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="UnstableStarCore" rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="UnstableStarCore_1_0" geometry={nodes.UnstableStarCore_1_0.geometry} material={materials.material} />
          </group>
          <group name="UnstableStarref" rotation={[-Math.PI / 2, 0, 0]} scale={1.01}>
            <mesh name="UnstableStarref_2_0" geometry={nodes.UnstableStarref_2_0.geometry} material={materials.material_1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/MyBlogWeb/sun-transformed.glb')
